services:
  - type: worker
    name: rami-levy-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ALLOWED_TELEGRAM_IDS
        sync: false
      - key: RAMI_LEVY_STORE_ID
        value: 331
      - key: RAMI_LEVY_API_KEY
        sync: false
      - key: RAMI_LEVY_ECOM_TOKEN
        sync: false
      - key: RAMI_LEVY_COOKIE
        sync: false
      - key: NODE_ENV
        value: production
